import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { SetStateAction, useState } from "react";

import { api } from "~/utils/api";
//this is the home page
const Home: NextPage = () => {
  const user = useUser();
  //this is home page. Created user variable which is the useUser hook from clerk.
  //trpc lets you create server functions that run on a vercel server. Fetch data from database so you can get data in the rigth shape without having the user to run the database code themselves

  const { data } = api.user.getAll.useQuery();
  console.log(data);
  const [message, setMessage] = useState("");

  const [updated, setUpdated] = useState("");

  const handleChange = (event: {
    target: { value: SetStateAction<string> };
  }) => {
    setMessage(event.target.value);
  };

  const handleKeyDown = (event: { key: string }) => {
    if (event.key === "Enter") {
      // 👇 Get input value
      setUpdated(message);
    }
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="flex justify-center">
                <SignOutButton />
              </div>
            )}
          </div>
          <div className="flex flex-col">
            {data?.map((user) => (
              <div key={user.id} className="border-b border-slate-400 p-8">
                {user.username}
              </div>
            ))}
          </div>
        </div>
      </main> */}
      <div>
        <input
          type="text"
          id="message"
          name="message"
          value={message}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
        />
      </div>
    </>
  );
};

export default Home;
